### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by emilianox** [pindexis/qfc#15]
Traceback (most recent call last):
  File "/home/emiliano/.qfc/bin/qfc", line 33, in <module>
    parse_arguments()
  File "/home/emiliano/.qfc/bin/qfc", line 16, in parse_arguments
    return args.func(args)
  File "/home/emiliano/.qfc/bin/qfc", line 19, in cmd_get
    output = core.get_selected_command_or_input(args.search)
  File "/home/emiliano/.qfc/bin/../qfc/core.py", line 12, in get_selected_command_or_input
    ui.refresh(state)
  File "/home/emiliano/.qfc/bin/../qfc/ui.py", line 20, in refresh
    lines, num_rows = _construct_output(state)
  File "/home/emiliano/.qfc/bin/../qfc/ui.py", line 45, in _construct_output
    fm = ' '+str(m)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/emiliano/.qfc/bin/qfc", line 33, in <module>
    parse_arguments()
  File "/home/emiliano/.qfc/bin/qfc", line 16, in parse_arguments
    return args.func(args)
  File "/home/emiliano/.qfc/bin/qfc", line 19, in cmd_get
    output = core.get_selected_command_or_input(args.search)
  File "/home/emiliano/.qfc/bin/../qfc/core.py", line 12, in get_selected_command_or_input
    ui.refresh(state)
  File "/home/emiliano/.qfc/bin/../qfc/ui.py", line 20, in refresh
    lines, num_rows = _construct_output(state)
  File "/home/emiliano/.qfc/bin/../qfc/ui.py", line 45, in _construct_output
    fm = ' '+str(m)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 2: ordinal not in range(128)

Version Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Test in Guake and bash  2.1 at elementary freya

**Comment by pindexis** [comment]
9e3db84120d87231c54b1bd763285e4f1b761756 should fix this.

**Comment by emilianox** [comment]
That works! Thanks! :+1:
