### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by Ahiknsr** [pindexis/qfc#5]
I have installed qfc using the method described [here](https://pindexis.github.io/qfc/#installation) , when i tried to run qfc it's throwing a error 
Traceback (most recent call last):
  File "/home/user/.qfc/bin/qfc", line 34, in <module>
    parse_arguments()
  File "/home/user/.qfc/bin/qfc", line 17, in parse_arguments
    return args.func(args)
  File "/home/user/.qfc/bin/qfc", line 20, in cmd_get
    output = core.get_selected_command_or_input(args.search)
  File "/home/user/.qfc/bin/../qfc/core.py", line 11, in get_selected_command_or_input
    state = State(search)
  File "/home/user/.qfc/bin/../qfc/core.py", line 62, in **init**
    self.set_input(default_input)
  File "/home/user/.qfc/bin/../qfc/core.py", line 72, in set_input
    self._update()
  File "/home/user/.qfc/bin/../qfc/core.py", line 105, in _update
    self.matches = get_matches(os.getcwd(),self.input)
  File "/home/user/.qfc/bin/../qfc/core.py", line 128, in get_matches
    source_files = dirhandler.get_source_files(start_dir)
  File "/home/user/.qfc/bin/../qfc/dirhandler.py", line 104, in get_source_files
    return default.get_source_files(directory)
  File "/home/user/.qfc/bin/../qfc/dirhandler.py", line 82, in get_source_files
    self._cache[start_dir] = self._walk_down(start_dir)
  File "/home/user/.qfc/bin/../qfc/dirhandler.py", line 77, in _walk_down
    files = out.split('\n')
TypeError: 'str' does not support the buffer interface

python version : 3.4.3
bash version : 4.3.39

**Comment by pindexis** [comment]
This should be fixed. can you confirm?

**Comment by Ahiknsr** [comment]
qfc working fine with the latest update . :+1:
