### ISSUE TITLE
Doesn't work on systems where `/usr/bin/python` is Python 3 (issue with ansi module)

### ISSUE THREAD

**Issue by jasonmhite** [pindexis/qfc#6]
On my system (Arch Linux), `python` is `python3`. Running qfc throws an exception:

```
Traceback (most recent call last):
  File "/home/jmhite/.qfc/bin/qfc", line 34, in <module>
    parse_arguments()
  File "/home/jmhite/.qfc/bin/qfc", line 17, in parse_arguments
    return args.func(args)
  File "/home/jmhite/.qfc/bin/qfc", line 20, in cmd_get
    output = core.get_selected_command_or_input(args.search)
  File "/home/jmhite/.qfc/bin/../qfc/core.py", line 13, in get_selected_command_or_input
    ui.refresh(state)
  File "/home/jmhite/.qfc/bin/../qfc/ui.py", line 19, in refresh
    erase()
  File "/home/jmhite/.qfc/bin/../qfc/ui.py", line 14, in erase
    ansi.move_cursor_line_beggining()
Attribute Error: 'module' object has no attribute 'move_cursor_line_beggining'
```

This actually looks to be an issue with the Py3k version of the ansi having changed the API. In any event, changing the shebang line in `qfc` to `#!/usr/bin/env python2` fixes it.

**Comment by pindexis** [comment]
this should be fixed by now.

**Comment by jasonmhite** [comment]
Thanks, looks good.
